version: '3.8'

services:
  app:
    image: lgy-ai-code:latest
    container_name: lgy-ai-code
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9527:9527"
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    restart: unless-stopped
    networks:
      - backend
      # 新增环境变量，覆盖应用配置
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/lgy_ai_code?useUnicode=true&characterEncoding=utf-8&useSSL=false
      - SPRING_REDIS_HOST=host.docker.internal

networks:
  backend:
    driver: bridge

volumes:
  mysql_data:
