version: '3.8'

services:
  app:
    image: lgy-ai-code:latest
    container_name: lgy-ai-code
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9527:9527"
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    restart: unless-stopped
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  mysql_data:
