spring:
  application:
    name: lgy-ai-code
  profiles:
    active: dev

server:
  port: 9527
  servlet:
    context-path: /api #?????
    session:
      cookie:
        max-age: 1800

# springdoc-openapi????
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.lgy.controller
# knife4j???????????????
knife4j:
  enable: true
  setting:
    language: zh_cn

cos:
  client:
    host: https://lgy-ai-code-1313505823.cos.ap-beijing.myqcloud.com
    secretId: AKIDEIBxXu65yiHgttgIiuuhJj2A4lGYcXFn
    secretKey: Ro4JOSVP6aswnRs66sSpMwJUUIvLenjS
    region: ap-beijing
    bucket: lgy-ai-code-1313505823