spring:
  application:
    name: lgy-ai-code
  profiles:
    active: dev

server:
  port: 9527
  servlet:
    context-path: /api #?????
    session:
      cookie:
        max-age: 1800

# springdoc-openapi????
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.lgy.controller
# knife4j???????????????
knife4j:
  enable: true
  setting:
    language: zh_cn
