spring:
  application:
    name: lgy-ai-code
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lgy_ai_code
    username: root
    password: gy123456
  # redis
  data:
    redis:
      host: localhost
      port: 6379
      password:
      ttl: 3600
      database: 0
  session:
    store-type: redis
    timeout: 1800
server:
  port: 9527
  servlet:
    context-path: /api #?????
    session:
      cookie:
        max-age: 1800

# springdoc-openapi????
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.lgy.controller
# knife4j???????????????
knife4j:
  enable: true
  setting:
    language: zh_cn

langchain4j:
  open-ai:
    chat-model:
      base-url: https://api.deepseek.com
      api-key: sk-ad0f12d1bd08428995c1b359f52b3ec6
      log-requests: true
      log-responses: true
      model-name: deepseek-chat
    routing-chat-model:
      base-url: https://api.deepseek.com
      api-key: sk-ad0f12d1bd08428995c1b359f52b3ec6
      model-name: deepseek-chat
      log-requests: true
      log-responses: true
    streaming-chat-model:
      base-url: https://api.deepseek.com
      api-key: sk-ad0f12d1bd08428995c1b359f52b3ec6
      log-requests: true
      log-responses: true
      model-name: deepseek-chat
    reasoning-streaming-chat-model:
      base-url: https://api.deepseek.com
      api-key: sk-ad0f12d1bd08428995c1b359f52b3ec6
      log-requests: true
      log-responses: true
      model-name: deepseek-chat

cos:
  client:
      host: https://lgy-ai-code-1313505823.cos.ap-beijing.myqcloud.com
      secretId: AKIDEIBxXu65yiHgttgIiuuhJj2A4lGYcXFn
      secretKey: Ro4JOSVP6aswnRs66sSpMwJUUIvLenjS
      region: ap-beijing
      bucket: lgy-ai-code-1313505823